// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TémaLab.Data;

namespace TémaLab.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200518080132_InitialDBSchema")]
    partial class InitialDBSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TémaLab.Data.DTOs.CompetitionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CompetitionDto");
                });

            modelBuilder.Entity("TémaLab.Data.DTOs.PostDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PostDto");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostDtoId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostDtoId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Szia igen minden kérdésedben nagyon szívesen segítek",
                            PostId = 1,
                            UserId = 13,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "uhhh.... Az lenne az első kérédésem hogyan kell jétszani ? ",
                            PostId = 1,
                            UserId = 2,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Content = "ohhh haver én a mono blura esküszök sokkal élvezetesebb azzal a játék....",
                            PostId = 2,
                            UserId = 11,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is our first competition gonna be at",
                            Title = "First Competition",
                            UserId = 1,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is our seccond competition. created by",
                            Title = "Seccond Competition",
                            UserId = 15,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Sziasztok ugy gondolom itt az ideje hogy sörözünk egyett közösen!!!",
                            Title = "Sörözünk !",
                            UserId = 7,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TémaLab.Data.Entities.EventParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("EventParticipations");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Friendship", b =>
                {
                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("User1Id", "User2Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Friendship");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<int?>("PostDtoId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostDtoId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompetitionDtoId")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionDtoId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("UserId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Helló helló szasztok új vagyok még a weboldalon tudnátok segíteni ? Köszi.",
                            UserId = 2,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Sziasztok a legjobb Mono Red decket keresem tudnátok segíteni ? köszii...",
                            UserId = 3,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TémaLab.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MTGACode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "cdf6ac2a-5ede-4346-abd3-d67e2970049d",
                            Email = "peti@mail.hu",
                            EmailConfirmed = false,
                            Introduction = "Én vagyok a Peti",
                            LockoutEnabled = false,
                            MTGACode = "kód",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Kovács Péter",
                            score = 0
                        },
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "110defbb-f869-426a-8705-458a97dc6fc4",
                            Email = "justo.sit.amet@Pellentesquetincidunttempus.ca",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
                            LockoutEnabled = false,
                            MTGACode = "B7S 4R4",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Melodie",
                            score = 14567
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "85297906-9e5b-4b43-b5ca-22abe364782c",
                            Email = "est.vitae.sodales@tortor.com",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
                            LockoutEnabled = false,
                            MTGACode = "P3N 8J9",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Nathaniel",
                            score = 2347
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "e1e0f5b6-6cf5-4ed2-bda5-3edbdc672fb2",
                            Email = "et.magnis@estmollisnon.net",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing",
                            LockoutEnabled = false,
                            MTGACode = "O8R 4J2",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Maggy",
                            score = 678
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "8821fb2e-809e-4051-9244-905a59f87aa9",
                            Email = "Duis.cursus.diam@IncondimentumDonec.org",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet,",
                            LockoutEnabled = false,
                            MTGACode = "J0T 9E2",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Reagan",
                            score = 8732
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "3c7a092c-962d-4972-8f18-5c7c0f311adf",
                            Email = "id.erat@eros.com",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                            LockoutEnabled = false,
                            MTGACode = "X4B 4E1",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Gil",
                            score = 239874
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "ee3dcdf0-6f73-49f3-b99e-c61a545cc7c4",
                            Email = "turpis@montesnasceturridiculus.edu",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
                            LockoutEnabled = false,
                            MTGACode = "V8B 7U0",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Armand",
                            score = 293
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "4ac7a3e1-20ff-4eaa-8058-ff0edb5aaff2",
                            Email = "sem.eget@sollicitudinamalesuada.org",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
                            LockoutEnabled = false,
                            MTGACode = "V3J 1V4",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Bruno",
                            score = 23987
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "2fbd852e-a8b7-41a6-88b8-116025f8c2cd",
                            Email = "nec.quam.Curabitur@dictum.org",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
                            LockoutEnabled = false,
                            MTGACode = "I7C 3T4",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Patrick",
                            score = 235
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "579b5a8a-1c77-49d7-bf7d-d1c2c7536902",
                            Email = "eget@sociosqu.co.uk",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
                            LockoutEnabled = false,
                            MTGACode = "M7S 7Z3",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Sasha",
                            score = 89723
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "dc0473b9-1016-4f40-8d4c-49580d9b169f",
                            Email = "posuere.at@telluseuaugue.edu",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
                            LockoutEnabled = false,
                            MTGACode = "Y9K 8I0",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Nerea",
                            score = 2485
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "761e0a42-80e9-4e77-81ae-a236472c5773",
                            Email = "arcu.ac.orci@Nuncac.ca",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer",
                            LockoutEnabled = false,
                            MTGACode = "I1Q 2P3",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Destiny",
                            score = 23498
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "c0046278-6fdb-45fb-a1eb-a05a1768ba09",
                            Email = "Sed.diam@enimcommodo.org",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing",
                            LockoutEnabled = false,
                            MTGACode = "N7S 9B7",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Megan",
                            score = 8735
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "7261e533-5d77-4dd9-b51b-9ecb42746874",
                            Email = "nec.tempus.mauris@estac.ca",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
                            LockoutEnabled = false,
                            MTGACode = "Y1Z 8D5",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Dorian",
                            score = 32197
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "5614b9ff-a173-42c9-8b45-01bc918a0bd1",
                            Email = "lobortis.ultrices.Vivamus@feugiat.net",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum",
                            LockoutEnabled = false,
                            MTGACode = "I6G 4F6",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Preston",
                            score = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.DTOs.CompetitionDto", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.DTOs.PostDto", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Comment", b =>
                {
                    b.HasOne("TémaLab.Data.DTOs.PostDto", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Competition", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("Competitions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Event", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.EventParticipation", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.Event", "Event")
                        .WithMany("eventParticipations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("EventParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Friendship", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", "User1")
                        .WithMany("Friendships1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.Entities.User", "User2")
                        .WithMany("Friendships2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Like", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.DTOs.PostDto", null)
                        .WithMany("Likes")
                        .HasForeignKey("PostDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Participation", b =>
                {
                    b.HasOne("TémaLab.Data.DTOs.CompetitionDto", null)
                        .WithMany("Participations")
                        .HasForeignKey("CompetitionDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.Competition", "Competition")
                        .WithMany("Participations")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Post", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
