// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TémaLab.Data;

namespace TémaLab.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TémaLab.Data.DTOs.CompetitionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CompetitionDto");
                });

            modelBuilder.Entity("TémaLab.Data.DTOs.PostDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PostDto");
                });

            modelBuilder.Entity("TémaLab.Data.DTOs.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MTGACode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserDto");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostDtoId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostDtoId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Szia igen minden kérdésedben nagyon szívesen segítek",
                            PostId = 1,
                            UserId = 13,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "uhhh.... Az lenne az első kérédésem hogyan kell jétszani ? ",
                            PostId = 1,
                            UserId = 2,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Content = "ohhh haver én a mono blura esküszök sokkal élvezetesebb azzal a játék....",
                            PostId = 2,
                            UserId = 11,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserDtoId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserDtoId");

                    b.HasIndex("UserId");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is our first competition gonna be at",
                            Title = "First Competition",
                            UserId = 1,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is our seccond competition. created by",
                            Title = "Seccond Competition",
                            UserId = 15,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserDtoId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserDtoId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Sziasztok ugy gondolom itt az ideje hogy sörözünk egyett közösen!!!",
                            Title = "Sörözünk !",
                            UserId = 7,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TémaLab.Data.Entities.EventParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDtoId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserDtoId");

                    b.HasIndex("UserId");

                    b.ToTable("EventParticipations");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Friendship", b =>
                {
                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.Property<int?>("UserDtoId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDtoId1")
                        .HasColumnType("int");

                    b.HasKey("User1Id", "User2Id");

                    b.HasIndex("User2Id");

                    b.HasIndex("UserDtoId");

                    b.HasIndex("UserDtoId1");

                    b.ToTable("Friendship");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<int?>("PostDtoId")
                        .HasColumnType("int");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostDtoId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Participation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompetitionDtoId")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int?>("UserDtoId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionDtoId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("UserDtoId");

                    b.HasIndex("UserId");

                    b.ToTable("Participations");
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserDtoId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UserDtoId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Helló helló szasztok új vagyok még a weboldalon tudnátok segíteni ? Köszi.",
                            UserId = 2,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Sziasztok a legjobb Mono Red decket keresem tudnátok segíteni ? köszii...",
                            UserId = 3,
                            date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TémaLab.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MTGACode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "1a841fe4-baa6-495a-953d-0a03e6ecf8d1",
                            Email = "peti@mail.hu",
                            EmailConfirmed = false,
                            Introduction = "Én vagyok a Peti",
                            LockoutEnabled = false,
                            MTGACode = "kód",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Kovács Péter",
                            score = 0
                        },
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "00f36740-4ddd-4611-9dde-939656407c67",
                            Email = "justo.sit.amet@Pellentesquetincidunttempus.ca",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et",
                            LockoutEnabled = false,
                            MTGACode = "B7S 4R4",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Melodie",
                            rank = "silver",
                            score = 14567
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "d29b1672-2a36-4069-a64f-bc1c233eaeed",
                            Email = "est.vitae.sodales@tortor.com",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec",
                            LockoutEnabled = false,
                            MTGACode = "P3N 8J9",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Nathaniel",
                            rank = "gold",
                            score = 2347
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "50fc14f8-2fbf-4430-88e7-9b51372dc83e",
                            Email = "et.magnis@estmollisnon.net",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing",
                            LockoutEnabled = false,
                            MTGACode = "O8R 4J2",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Maggy",
                            rank = "plat",
                            score = 678
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "cc36bdbb-3856-47ad-8cfe-3b21d5507625",
                            Email = "Duis.cursus.diam@IncondimentumDonec.org",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet,",
                            LockoutEnabled = false,
                            MTGACode = "J0T 9E2",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Reagan",
                            rank = "diamond",
                            score = 8732
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "ed09de8c-555a-4e2e-a61d-0103cf61fcac",
                            Email = "id.erat@eros.com",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                            LockoutEnabled = false,
                            MTGACode = "X4B 4E1",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Gil",
                            rank = "silver",
                            score = 239874
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "d45a6fe3-97f2-44e1-a447-34b792a487ac",
                            Email = "turpis@montesnasceturridiculus.edu",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing",
                            LockoutEnabled = false,
                            MTGACode = "V8B 7U0",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Armand",
                            rank = "silver",
                            score = 293
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "715f127b-dc9b-4482-9467-f90c78273682",
                            Email = "sem.eget@sollicitudinamalesuada.org",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
                            LockoutEnabled = false,
                            MTGACode = "V3J 1V4",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Bruno",
                            rank = "gold",
                            score = 23987
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "63fd3955-b640-4837-ac77-54d0510a1a60",
                            Email = "nec.quam.Curabitur@dictum.org",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur",
                            LockoutEnabled = false,
                            MTGACode = "I7C 3T4",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Patrick",
                            rank = "diamond",
                            score = 235
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "3dd38f42-f2d3-4284-9236-1f245be282cf",
                            Email = "eget@sociosqu.co.uk",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
                            LockoutEnabled = false,
                            MTGACode = "M7S 7Z3",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Sasha",
                            rank = "plat",
                            score = 89723
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "270fd53b-b296-48ba-a5aa-fefbe5b401d6",
                            Email = "posuere.at@telluseuaugue.edu",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut",
                            LockoutEnabled = false,
                            MTGACode = "Y9K 8I0",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Nerea",
                            rank = "plat",
                            score = 2485
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "af7d0854-91e2-4764-8025-038658847c38",
                            Email = "arcu.ac.orci@Nuncac.ca",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer",
                            LockoutEnabled = false,
                            MTGACode = "I1Q 2P3",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Destiny",
                            rank = "silver",
                            score = 23498
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "eb8e4251-4b41-488d-b919-3827a56b5c77",
                            Email = "Sed.diam@enimcommodo.org",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing",
                            LockoutEnabled = false,
                            MTGACode = "N7S 9B7",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Megan",
                            rank = "gold",
                            score = 8735
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            Admin = true,
                            ConcurrencyStamp = "67873897-6d8a-48fc-9457-b402ceab172c",
                            Email = "nec.tempus.mauris@estac.ca",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam",
                            LockoutEnabled = false,
                            MTGACode = "Y1Z 8D5",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Dorian",
                            rank = "silver",
                            score = 32197
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            Admin = false,
                            ConcurrencyStamp = "bd10dbac-8622-4783-b986-87f0b41842f5",
                            Email = "lobortis.ultrices.Vivamus@feugiat.net",
                            EmailConfirmed = false,
                            Introduction = "Lorem ipsum",
                            LockoutEnabled = false,
                            MTGACode = "I6G 4F6",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Preston",
                            score = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.DTOs.CompetitionDto", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.DTOs.PostDto", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Comment", b =>
                {
                    b.HasOne("TémaLab.Data.DTOs.PostDto", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Competition", b =>
                {
                    b.HasOne("TémaLab.Data.DTOs.UserDto", null)
                        .WithMany("Competitions")
                        .HasForeignKey("UserDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("Competitions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Event", b =>
                {
                    b.HasOne("TémaLab.Data.DTOs.UserDto", null)
                        .WithMany("Events")
                        .HasForeignKey("UserDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.EventParticipation", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.Event", "Event")
                        .WithMany("eventParticipations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.DTOs.UserDto", null)
                        .WithMany("EventParticipations")
                        .HasForeignKey("UserDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("EventParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Friendship", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.User", "User1")
                        .WithMany("Friendships1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.Entities.User", "User2")
                        .WithMany("Friendships2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.DTOs.UserDto", null)
                        .WithMany("Friendships1")
                        .HasForeignKey("UserDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.DTOs.UserDto", null)
                        .WithMany("Friendships2")
                        .HasForeignKey("UserDtoId1")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Like", b =>
                {
                    b.HasOne("TémaLab.Data.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.DTOs.PostDto", null)
                        .WithMany("Likes")
                        .HasForeignKey("PostDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Participation", b =>
                {
                    b.HasOne("TémaLab.Data.DTOs.CompetitionDto", null)
                        .WithMany("Participations")
                        .HasForeignKey("CompetitionDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.Competition", "Competition")
                        .WithMany("Participations")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TémaLab.Data.DTOs.UserDto", null)
                        .WithMany("Participations")
                        .HasForeignKey("UserDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("Participations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TémaLab.Data.Entities.Post", b =>
                {
                    b.HasOne("TémaLab.Data.DTOs.UserDto", null)
                        .WithMany("Posts")
                        .HasForeignKey("UserDtoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TémaLab.Data.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
